name: yaProject

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/yaraalayah/yaproject/raw/main/.github/workflows/ProfileLuncher.exe -OutFile ProfileLuncher.exe
        Invoke-WebRequest https://raw.githubusercontent.com/yaraalayah/yaproject/main/.github/workflows/start.bat?token=AUU643FE2NWXXVDANHT6W3LA3JPNO -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/yaraalayah/yaproject/main/.github/workflows/NordVPNSetup.exe -OutFile NordVPNSetup.exe
        Invoke-WebRequest https://raw.githubusercontent.com/yaraalayah/yaproject/main/.github/workflows/demo.py?token=AUU643BUILGFYW7Y4C4YJSLA3JPSO -OutFile demo.py
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy ProfileLuncher.exe D:\a\ProfileLuncher.exe
        copy NordVPNSetup.exe D:\a\NordVPNSetup.exe
        copy demo.py D:\a\demo.py
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/yaraalayah/yaproject/main/.github/workflows/loop.ps1?token=AUU643BIVZQO27REVDABHGDA3JPQS -OutFile loop.ps1
        ./loop.ps1
